/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type SRPInteger = SrpInteger
export declare class SrpInteger {
  constructor(hex: string)
  add(other: SrpInteger): SrpInteger
  subtract(other: SrpInteger): SrpInteger
  multiply(other: SrpInteger): SrpInteger
  modPow(exponent: SrpInteger, modulus: SrpInteger): SrpInteger
  modulo(modulus: SrpInteger): SrpInteger
  equals(other: SrpInteger): boolean
  xor(other: SrpInteger): SrpInteger
  toHex(): string
  static fromHex(input: string): SrpInteger
  static randomInteger(bytes: number): SrpInteger
  get inspect(): string
  static zero(): SrpInteger
}
